#!/bin/bash

set -e

. versions
docker build \
	-t osx-installer \
	-f Dockerfile.osx \
	--build-arg DOCKER_RELEASE_STAGE="${DOCKER_RELEASE_STAGE}" \
	--build-arg INSTALLER_VERSION="${INSTALLER_VERSION}" \
	--build-arg DOCKER_VERSION="${DOCKER_VERSION}" \
	--build-arg DOCKER_BUILDX_VERSION="${DOCKER_BUILDX_VERSION}" \
	--build-arg DOCKER_COMPOSE2_VERSION="${DOCKER_COMPOSE2_VERSION}" \
	--build-arg DOCKER_MACHINE_VERSION="${DOCKER_MACHINE_VERSION}" \
	--build-arg GITLAB_MACHINE_VERSION="${GITLAB_MACHINE_VERSION}" \
	--build-arg T2D_MACHINE_VERSION="${T2D_MACHINE_VERSION}" \
	--build-arg VBOX_VERSION="${VBOX_VERSION}" \
	--build-arg VBOX_REV="${VBOX_REV}" \
	--build-arg MIXPANEL_TOKEN="${MIXPANEL_TOKEN}" \
	.
CONTAINER="$(docker create osx-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/Toolbox2docker.pkg \
		dist/Toolbox2docker-${INSTALLER_VERSION}.pkg
docker rm "${CONTAINER}" 2>/dev/null || true
